# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchPersonalNameSubdivisionIn

    BatchPersonalNameSubdivisionIn(;
        personalNames=nothing,
    )

    - personalNames::Vector{PersonalNameSubdivisionIn}
"""
Base.@kwdef mutable struct BatchPersonalNameSubdivisionIn <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonalNameSubdivisionIn} }

    function BatchPersonalNameSubdivisionIn(personalNames, )
        OpenAPI.validate_property(BatchPersonalNameSubdivisionIn, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchPersonalNameSubdivisionIn

const _property_types_BatchPersonalNameSubdivisionIn = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{PersonalNameSubdivisionIn}", )
OpenAPI.property_type(::Type{ BatchPersonalNameSubdivisionIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchPersonalNameSubdivisionIn[name]))}

function check_required(o::BatchPersonalNameSubdivisionIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchPersonalNameSubdivisionIn }, name::Symbol, val)
end
