# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNameGeoZippedIn

    BatchFirstLastNameGeoZippedIn(;
        personalNames=nothing,
    )

    - personalNames::Vector{FirstLastNameGeoZippedIn}
"""
Base.@kwdef mutable struct BatchFirstLastNameGeoZippedIn <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNameGeoZippedIn} }

    function BatchFirstLastNameGeoZippedIn(personalNames, )
        OpenAPI.validate_property(BatchFirstLastNameGeoZippedIn, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchFirstLastNameGeoZippedIn

const _property_types_BatchFirstLastNameGeoZippedIn = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{FirstLastNameGeoZippedIn}", )
OpenAPI.property_type(::Type{ BatchFirstLastNameGeoZippedIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNameGeoZippedIn[name]))}

function check_required(o::BatchFirstLastNameGeoZippedIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNameGeoZippedIn }, name::Symbol, val)
end
