# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNamePhoneCodedOut
Represents the output of inferring the LIKELY country and phone code of personal names+phones.

    BatchFirstLastNamePhoneCodedOut(;
        personalNamesWithPhoneNumbers=nothing,
    )

    - personalNamesWithPhoneNumbers::Vector{FirstLastNamePhoneCodedOut} : Classified phone-coded names
"""
Base.@kwdef mutable struct BatchFirstLastNamePhoneCodedOut <: OpenAPI.APIModel
    personalNamesWithPhoneNumbers::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNamePhoneCodedOut} }

    function BatchFirstLastNamePhoneCodedOut(personalNamesWithPhoneNumbers, )
        OpenAPI.validate_property(BatchFirstLastNamePhoneCodedOut, Symbol("personalNamesWithPhoneNumbers"), personalNamesWithPhoneNumbers)
        return new(personalNamesWithPhoneNumbers, )
    end
end # type BatchFirstLastNamePhoneCodedOut

const _property_types_BatchFirstLastNamePhoneCodedOut = Dict{Symbol,String}(Symbol("personalNamesWithPhoneNumbers")=>"Vector{FirstLastNamePhoneCodedOut}", )
OpenAPI.property_type(::Type{ BatchFirstLastNamePhoneCodedOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNamePhoneCodedOut[name]))}

function check_required(o::BatchFirstLastNamePhoneCodedOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNamePhoneCodedOut }, name::Symbol, val)
end
