# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RegionOut

    RegionOut(;
        countriesAndRegions=nothing,
    )

    - countriesAndRegions::Vector{RegionISO} : List of countries and regions
"""
Base.@kwdef mutable struct RegionOut <: OpenAPI.APIModel
    countriesAndRegions::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{RegionISO} }

    function RegionOut(countriesAndRegions, )
        OpenAPI.validate_property(RegionOut, Symbol("countriesAndRegions"), countriesAndRegions)
        return new(countriesAndRegions, )
    end
end # type RegionOut

const _property_types_RegionOut = Dict{Symbol,String}(Symbol("countriesAndRegions")=>"Vector{RegionISO}", )
OpenAPI.property_type(::Type{ RegionOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RegionOut[name]))}

function check_required(o::RegionOut)
    true
end

function OpenAPI.validate_property(::Type{ RegionOut }, name::Symbol, val)
end
