# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchCommunityEngageOut

    BatchCommunityEngageOut(;
        engagementCandidates=nothing,
    )

    - engagementCandidates::Vector{CommunityEngageOut} : Classified community engagement candidates
"""
Base.@kwdef mutable struct BatchCommunityEngageOut <: OpenAPI.APIModel
    engagementCandidates::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{CommunityEngageOut} }

    function BatchCommunityEngageOut(engagementCandidates, )
        OpenAPI.validate_property(BatchCommunityEngageOut, Symbol("engagementCandidates"), engagementCandidates)
        return new(engagementCandidates, )
    end
end # type BatchCommunityEngageOut

const _property_types_BatchCommunityEngageOut = Dict{Symbol,String}(Symbol("engagementCandidates")=>"Vector{CommunityEngageOut}", )
OpenAPI.property_type(::Type{ BatchCommunityEngageOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchCommunityEngageOut[name]))}

function check_required(o::BatchCommunityEngageOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchCommunityEngageOut }, name::Symbol, val)
end
