# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNameSubdivisionIn

    BatchFirstLastNameSubdivisionIn(;
        personalNames=nothing,
    )

    - personalNames::Vector{FirstLastNameSubdivisionIn}
"""
Base.@kwdef mutable struct BatchFirstLastNameSubdivisionIn <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNameSubdivisionIn} }

    function BatchFirstLastNameSubdivisionIn(personalNames, )
        OpenAPI.validate_property(BatchFirstLastNameSubdivisionIn, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchFirstLastNameSubdivisionIn

const _property_types_BatchFirstLastNameSubdivisionIn = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{FirstLastNameSubdivisionIn}", )
OpenAPI.property_type(::Type{ BatchFirstLastNameSubdivisionIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNameSubdivisionIn[name]))}

function check_required(o::BatchFirstLastNameSubdivisionIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNameSubdivisionIn }, name::Symbol, val)
end
