# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchPersonalNameDiasporaedOut
Represents the output of inferring the LIKELY ethnicity from a personal name, given an country of residence.

    BatchPersonalNameDiasporaedOut(;
        personalNames=nothing,
    )

    - personalNames::Vector{PersonalNameDiasporaedOut} : Classified diaspora names
"""
Base.@kwdef mutable struct BatchPersonalNameDiasporaedOut <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonalNameDiasporaedOut} }

    function BatchPersonalNameDiasporaedOut(personalNames, )
        OpenAPI.validate_property(BatchPersonalNameDiasporaedOut, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchPersonalNameDiasporaedOut

const _property_types_BatchPersonalNameDiasporaedOut = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{PersonalNameDiasporaedOut}", )
OpenAPI.property_type(::Type{ BatchPersonalNameDiasporaedOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchPersonalNameDiasporaedOut[name]))}

function check_required(o::BatchPersonalNameDiasporaedOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchPersonalNameDiasporaedOut }, name::Symbol, val)
end
