# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNameGeoSubclassificationOut
Represents the output of inferring the LIKELY country subclassification (regional names).

    BatchFirstLastNameGeoSubclassificationOut(;
        personalNames=nothing,
    )

    - personalNames::Vector{FirstLastNameGeoSubclassificationOut} : Classified names at sub country level (region or state)
"""
Base.@kwdef mutable struct BatchFirstLastNameGeoSubclassificationOut <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNameGeoSubclassificationOut} }

    function BatchFirstLastNameGeoSubclassificationOut(personalNames, )
        OpenAPI.validate_property(BatchFirstLastNameGeoSubclassificationOut, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchFirstLastNameGeoSubclassificationOut

const _property_types_BatchFirstLastNameGeoSubclassificationOut = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{FirstLastNameGeoSubclassificationOut}", )
OpenAPI.property_type(::Type{ BatchFirstLastNameGeoSubclassificationOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNameGeoSubclassificationOut[name]))}

function check_required(o::BatchFirstLastNameGeoSubclassificationOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNameGeoSubclassificationOut }, name::Symbol, val)
end
