# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchPersonalNameGeoOut

    BatchPersonalNameGeoOut(;
        personalNames=nothing,
    )

    - personalNames::Vector{PersonalNameGeoOut} : Classified geo names
"""
Base.@kwdef mutable struct BatchPersonalNameGeoOut <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonalNameGeoOut} }

    function BatchPersonalNameGeoOut(personalNames, )
        OpenAPI.validate_property(BatchPersonalNameGeoOut, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchPersonalNameGeoOut

const _property_types_BatchPersonalNameGeoOut = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{PersonalNameGeoOut}", )
OpenAPI.property_type(::Type{ BatchPersonalNameGeoOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchPersonalNameGeoOut[name]))}

function check_required(o::BatchPersonalNameGeoOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchPersonalNameGeoOut }, name::Symbol, val)
end
