# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchPersonalNameParsedOut

    BatchPersonalNameParsedOut(;
        personalNames=nothing,
    )

    - personalNames::Vector{PersonalNameParsedOut} : Classified parsed names
"""
Base.@kwdef mutable struct BatchPersonalNameParsedOut <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonalNameParsedOut} }

    function BatchPersonalNameParsedOut(personalNames, )
        OpenAPI.validate_property(BatchPersonalNameParsedOut, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchPersonalNameParsedOut

const _property_types_BatchPersonalNameParsedOut = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{PersonalNameParsedOut}", )
OpenAPI.property_type(::Type{ BatchPersonalNameParsedOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchPersonalNameParsedOut[name]))}

function check_required(o::BatchPersonalNameParsedOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchPersonalNameParsedOut }, name::Symbol, val)
end
