# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchPersonalNameOriginedOut
Represents the output of inferring the LIKELY origin from a list of personal names.

    BatchPersonalNameOriginedOut(;
        personalNames=nothing,
    )

    - personalNames::Vector{PersonalNameOriginedOut} : Classified origined names
"""
Base.@kwdef mutable struct BatchPersonalNameOriginedOut <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonalNameOriginedOut} }

    function BatchPersonalNameOriginedOut(personalNames, )
        OpenAPI.validate_property(BatchPersonalNameOriginedOut, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchPersonalNameOriginedOut

const _property_types_BatchPersonalNameOriginedOut = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{PersonalNameOriginedOut}", )
OpenAPI.property_type(::Type{ BatchPersonalNameOriginedOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchPersonalNameOriginedOut[name]))}

function check_required(o::BatchPersonalNameOriginedOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchPersonalNameOriginedOut }, name::Symbol, val)
end
