# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""FirstLastNameGeoIn

    FirstLastNameGeoIn(;
        id=nothing,
        firstName=nothing,
        lastName=nothing,
        countryIso2=nothing,
    )

    - id::String
    - firstName::String
    - lastName::String
    - countryIso2::String
"""
Base.@kwdef mutable struct FirstLastNameGeoIn <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    firstName::Union{Nothing, String} = nothing
    lastName::Union{Nothing, String} = nothing
    countryIso2::Union{Nothing, String} = nothing

    function FirstLastNameGeoIn(id, firstName, lastName, countryIso2, )
        OpenAPI.validate_property(FirstLastNameGeoIn, Symbol("id"), id)
        OpenAPI.validate_property(FirstLastNameGeoIn, Symbol("firstName"), firstName)
        OpenAPI.validate_property(FirstLastNameGeoIn, Symbol("lastName"), lastName)
        OpenAPI.validate_property(FirstLastNameGeoIn, Symbol("countryIso2"), countryIso2)
        return new(id, firstName, lastName, countryIso2, )
    end
end # type FirstLastNameGeoIn

const _property_types_FirstLastNameGeoIn = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("firstName")=>"String", Symbol("lastName")=>"String", Symbol("countryIso2")=>"String", )
OpenAPI.property_type(::Type{ FirstLastNameGeoIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FirstLastNameGeoIn[name]))}

function check_required(o::FirstLastNameGeoIn)
    true
end

function OpenAPI.validate_property(::Type{ FirstLastNameGeoIn }, name::Symbol, val)
end
