# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PersonalNameGeoIn

    PersonalNameGeoIn(;
        id=nothing,
        name=nothing,
        countryIso2=nothing,
    )

    - id::String
    - name::String
    - countryIso2::String
"""
Base.@kwdef mutable struct PersonalNameGeoIn <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    countryIso2::Union{Nothing, String} = nothing

    function PersonalNameGeoIn(id, name, countryIso2, )
        OpenAPI.validate_property(PersonalNameGeoIn, Symbol("id"), id)
        OpenAPI.validate_property(PersonalNameGeoIn, Symbol("name"), name)
        OpenAPI.validate_property(PersonalNameGeoIn, Symbol("countryIso2"), countryIso2)
        return new(id, name, countryIso2, )
    end
end # type PersonalNameGeoIn

const _property_types_PersonalNameGeoIn = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("countryIso2")=>"String", )
OpenAPI.property_type(::Type{ PersonalNameGeoIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PersonalNameGeoIn[name]))}

function check_required(o::PersonalNameGeoIn)
    true
end

function OpenAPI.validate_property(::Type{ PersonalNameGeoIn }, name::Symbol, val)
end
