# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchCorridorIn

    BatchCorridorIn(;
        corridorFromTo=nothing,
    )

    - corridorFromTo::Vector{CorridorIn}
"""
Base.@kwdef mutable struct BatchCorridorIn <: OpenAPI.APIModel
    corridorFromTo::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{CorridorIn} }

    function BatchCorridorIn(corridorFromTo, )
        OpenAPI.validate_property(BatchCorridorIn, Symbol("corridorFromTo"), corridorFromTo)
        return new(corridorFromTo, )
    end
end # type BatchCorridorIn

const _property_types_BatchCorridorIn = Dict{Symbol,String}(Symbol("corridorFromTo")=>"Vector{CorridorIn}", )
OpenAPI.property_type(::Type{ BatchCorridorIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchCorridorIn[name]))}

function check_required(o::BatchCorridorIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchCorridorIn }, name::Symbol, val)
end
