# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PersonalNameGeoSubclassificationOut
Classified names at sub country level (region or state)

    PersonalNameGeoSubclassificationOut(;
        script=nothing,
        id=nothing,
        explanation=nothing,
        name=nothing,
        countryIso2=nothing,
        subClassification=nothing,
        subClassificationAlt=nothing,
        subclassificationTop=nothing,
        score=nothing,
        probabilityCalibrated=nothing,
        probabilityAltCalibrated=nothing,
    )

    - script::String
    - id::String
    - explanation::String
    - name::String : The input name.
    - countryIso2::String : The input country ISO2 code
    - subClassification::String : Most likely subclassification ISO_3166-2 code
    - subClassificationAlt::String : Second best alternative : subclassification ISO_3166-2 code
    - subclassificationTop::Vector{String} : List subclassification ISO_3166-2 codes (top 10)
    - score::Float64 : Compatibility to NamSor_v1 Origin score value. Higher score is better, but score is not normalized. Use calibratedProbability if available. 
    - probabilityCalibrated::Float64 : The calibrated probability for subclassification to have been guessed correctly. -1 &#x3D; still calibrating. 
    - probabilityAltCalibrated::Float64 : The calibrated probability for subclassification OR subclassificationAlt to have been guessed correctly. -1 &#x3D; still calibrating. 
"""
Base.@kwdef mutable struct PersonalNameGeoSubclassificationOut <: OpenAPI.APIModel
    script::Union{Nothing, String} = nothing
    id::Union{Nothing, String} = nothing
    explanation::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    countryIso2::Union{Nothing, String} = nothing
    subClassification::Union{Nothing, String} = nothing
    subClassificationAlt::Union{Nothing, String} = nothing
    subclassificationTop::Union{Nothing, Vector{String}} = nothing
    score::Union{Nothing, Float64} = nothing
    probabilityCalibrated::Union{Nothing, Float64} = nothing
    probabilityAltCalibrated::Union{Nothing, Float64} = nothing

    function PersonalNameGeoSubclassificationOut(script, id, explanation, name, countryIso2, subClassification, subClassificationAlt, subclassificationTop, score, probabilityCalibrated, probabilityAltCalibrated, )
        OpenAPI.validate_property(PersonalNameGeoSubclassificationOut, Symbol("script"), script)
        OpenAPI.validate_property(PersonalNameGeoSubclassificationOut, Symbol("id"), id)
        OpenAPI.validate_property(PersonalNameGeoSubclassificationOut, Symbol("explanation"), explanation)
        OpenAPI.validate_property(PersonalNameGeoSubclassificationOut, Symbol("name"), name)
        OpenAPI.validate_property(PersonalNameGeoSubclassificationOut, Symbol("countryIso2"), countryIso2)
        OpenAPI.validate_property(PersonalNameGeoSubclassificationOut, Symbol("subClassification"), subClassification)
        OpenAPI.validate_property(PersonalNameGeoSubclassificationOut, Symbol("subClassificationAlt"), subClassificationAlt)
        OpenAPI.validate_property(PersonalNameGeoSubclassificationOut, Symbol("subclassificationTop"), subclassificationTop)
        OpenAPI.validate_property(PersonalNameGeoSubclassificationOut, Symbol("score"), score)
        OpenAPI.validate_property(PersonalNameGeoSubclassificationOut, Symbol("probabilityCalibrated"), probabilityCalibrated)
        OpenAPI.validate_property(PersonalNameGeoSubclassificationOut, Symbol("probabilityAltCalibrated"), probabilityAltCalibrated)
        return new(script, id, explanation, name, countryIso2, subClassification, subClassificationAlt, subclassificationTop, score, probabilityCalibrated, probabilityAltCalibrated, )
    end
end # type PersonalNameGeoSubclassificationOut

const _property_types_PersonalNameGeoSubclassificationOut = Dict{Symbol,String}(Symbol("script")=>"String", Symbol("id")=>"String", Symbol("explanation")=>"String", Symbol("name")=>"String", Symbol("countryIso2")=>"String", Symbol("subClassification")=>"String", Symbol("subClassificationAlt")=>"String", Symbol("subclassificationTop")=>"Vector{String}", Symbol("score")=>"Float64", Symbol("probabilityCalibrated")=>"Float64", Symbol("probabilityAltCalibrated")=>"Float64", )
OpenAPI.property_type(::Type{ PersonalNameGeoSubclassificationOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PersonalNameGeoSubclassificationOut[name]))}

function check_required(o::PersonalNameGeoSubclassificationOut)
    true
end

function OpenAPI.validate_property(::Type{ PersonalNameGeoSubclassificationOut }, name::Symbol, val)
    if name === Symbol("score")
        OpenAPI.validate_param(name, "PersonalNameGeoSubclassificationOut", :format, val, "double")
    end
    if name === Symbol("score")
        OpenAPI.validate_param(name, "PersonalNameGeoSubclassificationOut", :maximum, val, 100, false)
        OpenAPI.validate_param(name, "PersonalNameGeoSubclassificationOut", :minimum, val, 0, false)
    end
    if name === Symbol("probabilityCalibrated")
        OpenAPI.validate_param(name, "PersonalNameGeoSubclassificationOut", :format, val, "double")
    end
    if name === Symbol("probabilityCalibrated")
        OpenAPI.validate_param(name, "PersonalNameGeoSubclassificationOut", :maximum, val, 1, false)
        OpenAPI.validate_param(name, "PersonalNameGeoSubclassificationOut", :minimum, val, -1, false)
    end
    if name === Symbol("probabilityAltCalibrated")
        OpenAPI.validate_param(name, "PersonalNameGeoSubclassificationOut", :format, val, "double")
    end
    if name === Symbol("probabilityAltCalibrated")
        OpenAPI.validate_param(name, "PersonalNameGeoSubclassificationOut", :maximum, val, 1, false)
        OpenAPI.validate_param(name, "PersonalNameGeoSubclassificationOut", :minimum, val, -1, false)
    end
end
