# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""FirstLastNameGeoZippedIn

    FirstLastNameGeoZippedIn(;
        id=nothing,
        firstName=nothing,
        lastName=nothing,
        countryIso2=nothing,
        zipCode=nothing,
    )

    - id::String
    - firstName::String
    - lastName::String
    - countryIso2::String
    - zipCode::String
"""
Base.@kwdef mutable struct FirstLastNameGeoZippedIn <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    firstName::Union{Nothing, String} = nothing
    lastName::Union{Nothing, String} = nothing
    countryIso2::Union{Nothing, String} = nothing
    zipCode::Union{Nothing, String} = nothing

    function FirstLastNameGeoZippedIn(id, firstName, lastName, countryIso2, zipCode, )
        OpenAPI.validate_property(FirstLastNameGeoZippedIn, Symbol("id"), id)
        OpenAPI.validate_property(FirstLastNameGeoZippedIn, Symbol("firstName"), firstName)
        OpenAPI.validate_property(FirstLastNameGeoZippedIn, Symbol("lastName"), lastName)
        OpenAPI.validate_property(FirstLastNameGeoZippedIn, Symbol("countryIso2"), countryIso2)
        OpenAPI.validate_property(FirstLastNameGeoZippedIn, Symbol("zipCode"), zipCode)
        return new(id, firstName, lastName, countryIso2, zipCode, )
    end
end # type FirstLastNameGeoZippedIn

const _property_types_FirstLastNameGeoZippedIn = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("firstName")=>"String", Symbol("lastName")=>"String", Symbol("countryIso2")=>"String", Symbol("zipCode")=>"String", )
OpenAPI.property_type(::Type{ FirstLastNameGeoZippedIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FirstLastNameGeoZippedIn[name]))}

function check_required(o::FirstLastNameGeoZippedIn)
    true
end

function OpenAPI.validate_property(::Type{ FirstLastNameGeoZippedIn }, name::Symbol, val)
end
