# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNameCastegroupOut
Represents the output of inferring the LIKELY origin from a list of personal names.

    BatchFirstLastNameCastegroupOut(;
        personalNames=nothing,
    )

    - personalNames::Vector{FirstLastNameCastegroupOut} : Classified origined names
"""
Base.@kwdef mutable struct BatchFirstLastNameCastegroupOut <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNameCastegroupOut} }

    function BatchFirstLastNameCastegroupOut(personalNames, )
        OpenAPI.validate_property(BatchFirstLastNameCastegroupOut, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchFirstLastNameCastegroupOut

const _property_types_BatchFirstLastNameCastegroupOut = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{FirstLastNameCastegroupOut}", )
OpenAPI.property_type(::Type{ BatchFirstLastNameCastegroupOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNameCastegroupOut[name]))}

function check_required(o::BatchFirstLastNameCastegroupOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNameCastegroupOut }, name::Symbol, val)
end
