# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchNameGeoIn

    BatchNameGeoIn(;
        properNouns=nothing,
    )

    - properNouns::Vector{NameGeoIn}
"""
Base.@kwdef mutable struct BatchNameGeoIn <: OpenAPI.APIModel
    properNouns::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{NameGeoIn} }

    function BatchNameGeoIn(properNouns, )
        OpenAPI.validate_property(BatchNameGeoIn, Symbol("properNouns"), properNouns)
        return new(properNouns, )
    end
end # type BatchNameGeoIn

const _property_types_BatchNameGeoIn = Dict{Symbol,String}(Symbol("properNouns")=>"Vector{NameGeoIn}", )
OpenAPI.property_type(::Type{ BatchNameGeoIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchNameGeoIn[name]))}

function check_required(o::BatchNameGeoIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchNameGeoIn }, name::Symbol, val)
end
