# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNamePhoneNumberIn

    BatchFirstLastNamePhoneNumberIn(;
        personalNamesWithPhoneNumbers=nothing,
    )

    - personalNamesWithPhoneNumbers::Vector{FirstLastNamePhoneNumberIn}
"""
Base.@kwdef mutable struct BatchFirstLastNamePhoneNumberIn <: OpenAPI.APIModel
    personalNamesWithPhoneNumbers::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNamePhoneNumberIn} }

    function BatchFirstLastNamePhoneNumberIn(personalNamesWithPhoneNumbers, )
        OpenAPI.validate_property(BatchFirstLastNamePhoneNumberIn, Symbol("personalNamesWithPhoneNumbers"), personalNamesWithPhoneNumbers)
        return new(personalNamesWithPhoneNumbers, )
    end
end # type BatchFirstLastNamePhoneNumberIn

const _property_types_BatchFirstLastNamePhoneNumberIn = Dict{Symbol,String}(Symbol("personalNamesWithPhoneNumbers")=>"Vector{FirstLastNamePhoneNumberIn}", )
OpenAPI.property_type(::Type{ BatchFirstLastNamePhoneNumberIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNamePhoneNumberIn[name]))}

function check_required(o::BatchFirstLastNamePhoneNumberIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNamePhoneNumberIn }, name::Symbol, val)
end
