# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNamePhoneNumberGeoIn

    BatchFirstLastNamePhoneNumberGeoIn(;
        personalNamesWithPhoneNumbers=nothing,
    )

    - personalNamesWithPhoneNumbers::Vector{FirstLastNamePhoneNumberGeoIn}
"""
Base.@kwdef mutable struct BatchFirstLastNamePhoneNumberGeoIn <: OpenAPI.APIModel
    personalNamesWithPhoneNumbers::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNamePhoneNumberGeoIn} }

    function BatchFirstLastNamePhoneNumberGeoIn(personalNamesWithPhoneNumbers, )
        OpenAPI.validate_property(BatchFirstLastNamePhoneNumberGeoIn, Symbol("personalNamesWithPhoneNumbers"), personalNamesWithPhoneNumbers)
        return new(personalNamesWithPhoneNumbers, )
    end
end # type BatchFirstLastNamePhoneNumberGeoIn

const _property_types_BatchFirstLastNamePhoneNumberGeoIn = Dict{Symbol,String}(Symbol("personalNamesWithPhoneNumbers")=>"Vector{FirstLastNamePhoneNumberGeoIn}", )
OpenAPI.property_type(::Type{ BatchFirstLastNamePhoneNumberGeoIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNamePhoneNumberGeoIn[name]))}

function check_required(o::BatchFirstLastNamePhoneNumberGeoIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNamePhoneNumberGeoIn }, name::Symbol, val)
end
