# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CommunityEngageOptionOut

    CommunityEngageOptionOut(;
        genderFilter=nothing,
        ethnicityFilter=nothing,
        countryOutFilter=nothing,
        usRaceEthnicityFilter=nothing,
    )

    - genderFilter::Vector{String} : The gender filter (null to allow all)
    - ethnicityFilter::Vector{String} : The ethnicity filter (null to allow all)
    - countryOutFilter::Vector{String} : The output country filter (null to allow all)
    - usRaceEthnicityFilter::Vector{String} : The output US race/ethnicity filter (null to allow all)
"""
Base.@kwdef mutable struct CommunityEngageOptionOut <: OpenAPI.APIModel
    genderFilter::Union{Nothing, Vector{String}} = nothing
    ethnicityFilter::Union{Nothing, Vector{String}} = nothing
    countryOutFilter::Union{Nothing, Vector{String}} = nothing
    usRaceEthnicityFilter::Union{Nothing, Vector{String}} = nothing

    function CommunityEngageOptionOut(genderFilter, ethnicityFilter, countryOutFilter, usRaceEthnicityFilter, )
        OpenAPI.validate_property(CommunityEngageOptionOut, Symbol("genderFilter"), genderFilter)
        OpenAPI.validate_property(CommunityEngageOptionOut, Symbol("ethnicityFilter"), ethnicityFilter)
        OpenAPI.validate_property(CommunityEngageOptionOut, Symbol("countryOutFilter"), countryOutFilter)
        OpenAPI.validate_property(CommunityEngageOptionOut, Symbol("usRaceEthnicityFilter"), usRaceEthnicityFilter)
        return new(genderFilter, ethnicityFilter, countryOutFilter, usRaceEthnicityFilter, )
    end
end # type CommunityEngageOptionOut

const _property_types_CommunityEngageOptionOut = Dict{Symbol,String}(Symbol("genderFilter")=>"Vector{String}", Symbol("ethnicityFilter")=>"Vector{String}", Symbol("countryOutFilter")=>"Vector{String}", Symbol("usRaceEthnicityFilter")=>"Vector{String}", )
OpenAPI.property_type(::Type{ CommunityEngageOptionOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CommunityEngageOptionOut[name]))}

function check_required(o::CommunityEngageOptionOut)
    true
end

function OpenAPI.validate_property(::Type{ CommunityEngageOptionOut }, name::Symbol, val)
end
