# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNameGenderedOut
Represents the output of inferring the LIKELY gender from a list of personal names.

    BatchFirstLastNameGenderedOut(;
        personalNames=nothing,
    )

    - personalNames::Vector{FirstLastNameGenderedOut} : Classified genderized names
"""
Base.@kwdef mutable struct BatchFirstLastNameGenderedOut <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNameGenderedOut} }

    function BatchFirstLastNameGenderedOut(personalNames, )
        OpenAPI.validate_property(BatchFirstLastNameGenderedOut, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchFirstLastNameGenderedOut

const _property_types_BatchFirstLastNameGenderedOut = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{FirstLastNameGenderedOut}", )
OpenAPI.property_type(::Type{ BatchFirstLastNameGenderedOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNameGenderedOut[name]))}

function check_required(o::BatchFirstLastNameGenderedOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNameGenderedOut }, name::Symbol, val)
end
