# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchPersonalNameReligionedOut

    BatchPersonalNameReligionedOut(;
        personalNames=nothing,
    )

    - personalNames::Vector{PersonalNameReligionedOut} : religious-coded names
"""
Base.@kwdef mutable struct BatchPersonalNameReligionedOut <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonalNameReligionedOut} }

    function BatchPersonalNameReligionedOut(personalNames, )
        OpenAPI.validate_property(BatchPersonalNameReligionedOut, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchPersonalNameReligionedOut

const _property_types_BatchPersonalNameReligionedOut = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{PersonalNameReligionedOut}", )
OpenAPI.property_type(::Type{ BatchPersonalNameReligionedOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchPersonalNameReligionedOut[name]))}

function check_required(o::BatchPersonalNameReligionedOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchPersonalNameReligionedOut }, name::Symbol, val)
end
