# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchPersonalNameGeoSubdivisionIn

    BatchPersonalNameGeoSubdivisionIn(;
        personalNames=nothing,
    )

    - personalNames::Vector{PersonalNameGeoSubdivisionIn}
"""
Base.@kwdef mutable struct BatchPersonalNameGeoSubdivisionIn <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonalNameGeoSubdivisionIn} }

    function BatchPersonalNameGeoSubdivisionIn(personalNames, )
        OpenAPI.validate_property(BatchPersonalNameGeoSubdivisionIn, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchPersonalNameGeoSubdivisionIn

const _property_types_BatchPersonalNameGeoSubdivisionIn = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{PersonalNameGeoSubdivisionIn}", )
OpenAPI.property_type(::Type{ BatchPersonalNameGeoSubdivisionIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchPersonalNameGeoSubdivisionIn[name]))}

function check_required(o::BatchPersonalNameGeoSubdivisionIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchPersonalNameGeoSubdivisionIn }, name::Symbol, val)
end
