# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PersonalNameIn

    PersonalNameIn(;
        id=nothing,
        name=nothing,
    )

    - id::String
    - name::String
"""
Base.@kwdef mutable struct PersonalNameIn <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing

    function PersonalNameIn(id, name, )
        OpenAPI.validate_property(PersonalNameIn, Symbol("id"), id)
        OpenAPI.validate_property(PersonalNameIn, Symbol("name"), name)
        return new(id, name, )
    end
end # type PersonalNameIn

const _property_types_PersonalNameIn = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ PersonalNameIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PersonalNameIn[name]))}

function check_required(o::PersonalNameIn)
    true
end

function OpenAPI.validate_property(::Type{ PersonalNameIn }, name::Symbol, val)
end
