# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchNameMatchedOut

    BatchNameMatchedOut(;
        matchedNames=nothing,
    )

    - matchedNames::Vector{NameMatchedOut} : Classified matched names
"""
Base.@kwdef mutable struct BatchNameMatchedOut <: OpenAPI.APIModel
    matchedNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{NameMatchedOut} }

    function BatchNameMatchedOut(matchedNames, )
        OpenAPI.validate_property(BatchNameMatchedOut, Symbol("matchedNames"), matchedNames)
        return new(matchedNames, )
    end
end # type BatchNameMatchedOut

const _property_types_BatchNameMatchedOut = Dict{Symbol,String}(Symbol("matchedNames")=>"Vector{NameMatchedOut}", )
OpenAPI.property_type(::Type{ BatchNameMatchedOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchNameMatchedOut[name]))}

function check_required(o::BatchNameMatchedOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchNameMatchedOut }, name::Symbol, val)
end
