# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""NameIn

    NameIn(;
        id=nothing,
        name=nothing,
    )

    - id::String
    - name::String
"""
Base.@kwdef mutable struct NameIn <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing

    function NameIn(id, name, )
        OpenAPI.validate_property(NameIn, Symbol("id"), id)
        OpenAPI.validate_property(NameIn, Symbol("name"), name)
        return new(id, name, )
    end
end # type NameIn

const _property_types_NameIn = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ NameIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_NameIn[name]))}

function check_required(o::NameIn)
    true
end

function OpenAPI.validate_property(::Type{ NameIn }, name::Symbol, val)
end
