# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchCorridorOut

    BatchCorridorOut(;
        corridorFromTo=nothing,
    )

    - corridorFromTo::Vector{CorridorOut} : Classified corridors
"""
Base.@kwdef mutable struct BatchCorridorOut <: OpenAPI.APIModel
    corridorFromTo::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{CorridorOut} }

    function BatchCorridorOut(corridorFromTo, )
        OpenAPI.validate_property(BatchCorridorOut, Symbol("corridorFromTo"), corridorFromTo)
        return new(corridorFromTo, )
    end
end # type BatchCorridorOut

const _property_types_BatchCorridorOut = Dict{Symbol,String}(Symbol("corridorFromTo")=>"Vector{CorridorOut}", )
OpenAPI.property_type(::Type{ BatchCorridorOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchCorridorOut[name]))}

function check_required(o::BatchCorridorOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchCorridorOut }, name::Symbol, val)
end
