# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PersonalNameUSRaceEthnicityOut
Represents the output of inferring the LIKELY US &#39;race/ethnicity&#39; from a personal name, given US country of residence and (optionally) a ZIP5 code.

    PersonalNameUSRaceEthnicityOut(;
        script=nothing,
        id=nothing,
        explanation=nothing,
        name=nothing,
        raceEthnicityAlt=nothing,
        raceEthnicity=nothing,
        score=nothing,
        raceEthnicitiesTop=nothing,
        probabilityCalibrated=nothing,
        probabilityAltCalibrated=nothing,
    )

    - script::String
    - id::String
    - explanation::String
    - name::String : The input name.
    - raceEthnicityAlt::String : Second most likely US &#39;race&#39;/ethnicity
    - raceEthnicity::String : Most likely US &#39;race&#39;/ethnicity
    - score::Float64 : Higher score is better, but score is not normalized. Use calibratedProbability if available. 
    - raceEthnicitiesTop::Vector{String} : List &#39;race&#39;/ethnicities
    - probabilityCalibrated::Float64 : The calibrated probability for raceEthnicity to have been guessed correctly. -1 &#x3D; still calibrating. 
    - probabilityAltCalibrated::Float64 : The calibrated probability for raceEthnicity OR raceEthnicityAlt to have been guessed correctly. -1 &#x3D; still calibrating. 
"""
Base.@kwdef mutable struct PersonalNameUSRaceEthnicityOut <: OpenAPI.APIModel
    script::Union{Nothing, String} = nothing
    id::Union{Nothing, String} = nothing
    explanation::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    raceEthnicityAlt::Union{Nothing, String} = nothing
    raceEthnicity::Union{Nothing, String} = nothing
    score::Union{Nothing, Float64} = nothing
    raceEthnicitiesTop::Union{Nothing, Vector{String}} = nothing
    probabilityCalibrated::Union{Nothing, Float64} = nothing
    probabilityAltCalibrated::Union{Nothing, Float64} = nothing

    function PersonalNameUSRaceEthnicityOut(script, id, explanation, name, raceEthnicityAlt, raceEthnicity, score, raceEthnicitiesTop, probabilityCalibrated, probabilityAltCalibrated, )
        OpenAPI.validate_property(PersonalNameUSRaceEthnicityOut, Symbol("script"), script)
        OpenAPI.validate_property(PersonalNameUSRaceEthnicityOut, Symbol("id"), id)
        OpenAPI.validate_property(PersonalNameUSRaceEthnicityOut, Symbol("explanation"), explanation)
        OpenAPI.validate_property(PersonalNameUSRaceEthnicityOut, Symbol("name"), name)
        OpenAPI.validate_property(PersonalNameUSRaceEthnicityOut, Symbol("raceEthnicityAlt"), raceEthnicityAlt)
        OpenAPI.validate_property(PersonalNameUSRaceEthnicityOut, Symbol("raceEthnicity"), raceEthnicity)
        OpenAPI.validate_property(PersonalNameUSRaceEthnicityOut, Symbol("score"), score)
        OpenAPI.validate_property(PersonalNameUSRaceEthnicityOut, Symbol("raceEthnicitiesTop"), raceEthnicitiesTop)
        OpenAPI.validate_property(PersonalNameUSRaceEthnicityOut, Symbol("probabilityCalibrated"), probabilityCalibrated)
        OpenAPI.validate_property(PersonalNameUSRaceEthnicityOut, Symbol("probabilityAltCalibrated"), probabilityAltCalibrated)
        return new(script, id, explanation, name, raceEthnicityAlt, raceEthnicity, score, raceEthnicitiesTop, probabilityCalibrated, probabilityAltCalibrated, )
    end
end # type PersonalNameUSRaceEthnicityOut

const _property_types_PersonalNameUSRaceEthnicityOut = Dict{Symbol,String}(Symbol("script")=>"String", Symbol("id")=>"String", Symbol("explanation")=>"String", Symbol("name")=>"String", Symbol("raceEthnicityAlt")=>"String", Symbol("raceEthnicity")=>"String", Symbol("score")=>"Float64", Symbol("raceEthnicitiesTop")=>"Vector{String}", Symbol("probabilityCalibrated")=>"Float64", Symbol("probabilityAltCalibrated")=>"Float64", )
OpenAPI.property_type(::Type{ PersonalNameUSRaceEthnicityOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PersonalNameUSRaceEthnicityOut[name]))}

function check_required(o::PersonalNameUSRaceEthnicityOut)
    true
end

function OpenAPI.validate_property(::Type{ PersonalNameUSRaceEthnicityOut }, name::Symbol, val)
    if name === Symbol("raceEthnicityAlt")
        OpenAPI.validate_param(name, "PersonalNameUSRaceEthnicityOut", :enum, val, ["W_NL", "HL", "A", "B_NL", "AI_AN", "PI"])
    end
    if name === Symbol("raceEthnicity")
        OpenAPI.validate_param(name, "PersonalNameUSRaceEthnicityOut", :enum, val, ["W_NL", "HL", "A", "B_NL", "AI_AN", "PI"])
    end
    if name === Symbol("score")
        OpenAPI.validate_param(name, "PersonalNameUSRaceEthnicityOut", :format, val, "double")
    end
    if name === Symbol("score")
        OpenAPI.validate_param(name, "PersonalNameUSRaceEthnicityOut", :maximum, val, 100, false)
        OpenAPI.validate_param(name, "PersonalNameUSRaceEthnicityOut", :minimum, val, 0, false)
    end
    if name === Symbol("probabilityCalibrated")
        OpenAPI.validate_param(name, "PersonalNameUSRaceEthnicityOut", :format, val, "double")
    end
    if name === Symbol("probabilityCalibrated")
        OpenAPI.validate_param(name, "PersonalNameUSRaceEthnicityOut", :maximum, val, 1, false)
        OpenAPI.validate_param(name, "PersonalNameUSRaceEthnicityOut", :minimum, val, -1, false)
    end
    if name === Symbol("probabilityAltCalibrated")
        OpenAPI.validate_param(name, "PersonalNameUSRaceEthnicityOut", :format, val, "double")
    end
    if name === Symbol("probabilityAltCalibrated")
        OpenAPI.validate_param(name, "PersonalNameUSRaceEthnicityOut", :maximum, val, 1, false)
        OpenAPI.validate_param(name, "PersonalNameUSRaceEthnicityOut", :minimum, val, -1, false)
    end
end
