# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""FirstLastNameGeoSubdivisionIn

    FirstLastNameGeoSubdivisionIn(;
        id=nothing,
        firstName=nothing,
        lastName=nothing,
        countryIso2=nothing,
        subdivisionIso=nothing,
    )

    - id::String
    - firstName::String
    - lastName::String
    - countryIso2::String
    - subdivisionIso::String
"""
Base.@kwdef mutable struct FirstLastNameGeoSubdivisionIn <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    firstName::Union{Nothing, String} = nothing
    lastName::Union{Nothing, String} = nothing
    countryIso2::Union{Nothing, String} = nothing
    subdivisionIso::Union{Nothing, String} = nothing

    function FirstLastNameGeoSubdivisionIn(id, firstName, lastName, countryIso2, subdivisionIso, )
        OpenAPI.validate_property(FirstLastNameGeoSubdivisionIn, Symbol("id"), id)
        OpenAPI.validate_property(FirstLastNameGeoSubdivisionIn, Symbol("firstName"), firstName)
        OpenAPI.validate_property(FirstLastNameGeoSubdivisionIn, Symbol("lastName"), lastName)
        OpenAPI.validate_property(FirstLastNameGeoSubdivisionIn, Symbol("countryIso2"), countryIso2)
        OpenAPI.validate_property(FirstLastNameGeoSubdivisionIn, Symbol("subdivisionIso"), subdivisionIso)
        return new(id, firstName, lastName, countryIso2, subdivisionIso, )
    end
end # type FirstLastNameGeoSubdivisionIn

const _property_types_FirstLastNameGeoSubdivisionIn = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("firstName")=>"String", Symbol("lastName")=>"String", Symbol("countryIso2")=>"String", Symbol("subdivisionIso")=>"String", )
OpenAPI.property_type(::Type{ FirstLastNameGeoSubdivisionIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FirstLastNameGeoSubdivisionIn[name]))}

function check_required(o::FirstLastNameGeoSubdivisionIn)
    true
end

function OpenAPI.validate_property(::Type{ FirstLastNameGeoSubdivisionIn }, name::Symbol, val)
end
