# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchPersonalNameGeoIn

    BatchPersonalNameGeoIn(;
        personalNames=nothing,
    )

    - personalNames::Vector{PersonalNameGeoIn}
"""
Base.@kwdef mutable struct BatchPersonalNameGeoIn <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonalNameGeoIn} }

    function BatchPersonalNameGeoIn(personalNames, )
        OpenAPI.validate_property(BatchPersonalNameGeoIn, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchPersonalNameGeoIn

const _property_types_BatchPersonalNameGeoIn = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{PersonalNameGeoIn}", )
OpenAPI.property_type(::Type{ BatchPersonalNameGeoIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchPersonalNameGeoIn[name]))}

function check_required(o::BatchPersonalNameGeoIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchPersonalNameGeoIn }, name::Symbol, val)
end
