# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNameIn

    BatchFirstLastNameIn(;
        personalNames=nothing,
    )

    - personalNames::Vector{FirstLastNameIn}
"""
Base.@kwdef mutable struct BatchFirstLastNameIn <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNameIn} }

    function BatchFirstLastNameIn(personalNames, )
        OpenAPI.validate_property(BatchFirstLastNameIn, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchFirstLastNameIn

const _property_types_BatchFirstLastNameIn = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{FirstLastNameIn}", )
OpenAPI.property_type(::Type{ BatchFirstLastNameIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNameIn[name]))}

function check_required(o::BatchFirstLastNameIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNameIn }, name::Symbol, val)
end
