# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchPersonalNameIn

    BatchPersonalNameIn(;
        personalNames=nothing,
    )

    - personalNames::Vector{PersonalNameIn}
"""
Base.@kwdef mutable struct BatchPersonalNameIn <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PersonalNameIn} }

    function BatchPersonalNameIn(personalNames, )
        OpenAPI.validate_property(BatchPersonalNameIn, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchPersonalNameIn

const _property_types_BatchPersonalNameIn = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{PersonalNameIn}", )
OpenAPI.property_type(::Type{ BatchPersonalNameIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchPersonalNameIn[name]))}

function check_required(o::BatchPersonalNameIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchPersonalNameIn }, name::Symbol, val)
end
