# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""NameGeoIn

    NameGeoIn(;
        id=nothing,
        name=nothing,
        countryIso2=nothing,
    )

    - id::String
    - name::String
    - countryIso2::String
"""
Base.@kwdef mutable struct NameGeoIn <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    countryIso2::Union{Nothing, String} = nothing

    function NameGeoIn(id, name, countryIso2, )
        OpenAPI.validate_property(NameGeoIn, Symbol("id"), id)
        OpenAPI.validate_property(NameGeoIn, Symbol("name"), name)
        OpenAPI.validate_property(NameGeoIn, Symbol("countryIso2"), countryIso2)
        return new(id, name, countryIso2, )
    end
end # type NameGeoIn

const _property_types_NameGeoIn = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("countryIso2")=>"String", )
OpenAPI.property_type(::Type{ NameGeoIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_NameGeoIn[name]))}

function check_required(o::NameGeoIn)
    true
end

function OpenAPI.validate_property(::Type{ NameGeoIn }, name::Symbol, val)
end
