# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""FirstLastNamePhoneNumberIn

    FirstLastNamePhoneNumberIn(;
        id=nothing,
        firstName=nothing,
        lastName=nothing,
        phoneNumber=nothing,
    )

    - id::String
    - firstName::String
    - lastName::String
    - phoneNumber::String
"""
Base.@kwdef mutable struct FirstLastNamePhoneNumberIn <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    firstName::Union{Nothing, String} = nothing
    lastName::Union{Nothing, String} = nothing
    phoneNumber::Union{Nothing, String} = nothing

    function FirstLastNamePhoneNumberIn(id, firstName, lastName, phoneNumber, )
        OpenAPI.validate_property(FirstLastNamePhoneNumberIn, Symbol("id"), id)
        OpenAPI.validate_property(FirstLastNamePhoneNumberIn, Symbol("firstName"), firstName)
        OpenAPI.validate_property(FirstLastNamePhoneNumberIn, Symbol("lastName"), lastName)
        OpenAPI.validate_property(FirstLastNamePhoneNumberIn, Symbol("phoneNumber"), phoneNumber)
        return new(id, firstName, lastName, phoneNumber, )
    end
end # type FirstLastNamePhoneNumberIn

const _property_types_FirstLastNamePhoneNumberIn = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("firstName")=>"String", Symbol("lastName")=>"String", Symbol("phoneNumber")=>"String", )
OpenAPI.property_type(::Type{ FirstLastNamePhoneNumberIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FirstLastNamePhoneNumberIn[name]))}

function check_required(o::FirstLastNamePhoneNumberIn)
    true
end

function OpenAPI.validate_property(::Type{ FirstLastNamePhoneNumberIn }, name::Symbol, val)
end
