# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNameDiasporaedOut
Represents the output of inferring the LIKELY ethnicity from a personal name, given an country of residence.

    BatchFirstLastNameDiasporaedOut(;
        personalNames=nothing,
    )

    - personalNames::Vector{FirstLastNameDiasporaedOut} : Classified diaspora names
"""
Base.@kwdef mutable struct BatchFirstLastNameDiasporaedOut <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNameDiasporaedOut} }

    function BatchFirstLastNameDiasporaedOut(personalNames, )
        OpenAPI.validate_property(BatchFirstLastNameDiasporaedOut, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchFirstLastNameDiasporaedOut

const _property_types_BatchFirstLastNameDiasporaedOut = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{FirstLastNameDiasporaedOut}", )
OpenAPI.property_type(::Type{ BatchFirstLastNameDiasporaedOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNameDiasporaedOut[name]))}

function check_required(o::BatchFirstLastNameDiasporaedOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNameDiasporaedOut }, name::Symbol, val)
end
