# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""APIUsageHistoryOut

    APIUsageHistoryOut(;
        detailedUsage=nothing,
    )

    - detailedUsage::Vector{APICounterV2Out} : Detailed usage as reported by the deduplicating API counter.
"""
Base.@kwdef mutable struct APIUsageHistoryOut <: OpenAPI.APIModel
    detailedUsage::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{APICounterV2Out} }

    function APIUsageHistoryOut(detailedUsage, )
        OpenAPI.validate_property(APIUsageHistoryOut, Symbol("detailedUsage"), detailedUsage)
        return new(detailedUsage, )
    end
end # type APIUsageHistoryOut

const _property_types_APIUsageHistoryOut = Dict{Symbol,String}(Symbol("detailedUsage")=>"Vector{APICounterV2Out}", )
OpenAPI.property_type(::Type{ APIUsageHistoryOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_APIUsageHistoryOut[name]))}

function check_required(o::APIUsageHistoryOut)
    true
end

function OpenAPI.validate_property(::Type{ APIUsageHistoryOut }, name::Symbol, val)
end
