# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CorridorOut
Represent multiple classifications for corridor sender and receiver (gender, country, origin, diaspora)

    CorridorOut(;
        id=nothing,
        FirstLastNameGenderedOut=nothing,
        FirstLastNameOriginedOut=nothing,
        FirstLastNameDiasporaedOut=nothing,
        script=nothing,
    )

    - id::String
    - FirstLastNameGenderedOut::FirstLastNameGenderedOut
    - FirstLastNameOriginedOut::FirstLastNameOriginedOut
    - FirstLastNameDiasporaedOut::FirstLastNameDiasporaedOut
    - script::String
"""
Base.@kwdef mutable struct CorridorOut <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    FirstLastNameGenderedOut = nothing # spec type: Union{ Nothing, FirstLastNameGenderedOut }
    FirstLastNameOriginedOut = nothing # spec type: Union{ Nothing, FirstLastNameOriginedOut }
    FirstLastNameDiasporaedOut = nothing # spec type: Union{ Nothing, FirstLastNameDiasporaedOut }
    script::Union{Nothing, String} = nothing

    function CorridorOut(id, FirstLastNameGenderedOut, FirstLastNameOriginedOut, FirstLastNameDiasporaedOut, script, )
        OpenAPI.validate_property(CorridorOut, Symbol("id"), id)
        OpenAPI.validate_property(CorridorOut, Symbol("FirstLastNameGenderedOut"), FirstLastNameGenderedOut)
        OpenAPI.validate_property(CorridorOut, Symbol("FirstLastNameOriginedOut"), FirstLastNameOriginedOut)
        OpenAPI.validate_property(CorridorOut, Symbol("FirstLastNameDiasporaedOut"), FirstLastNameDiasporaedOut)
        OpenAPI.validate_property(CorridorOut, Symbol("script"), script)
        return new(id, FirstLastNameGenderedOut, FirstLastNameOriginedOut, FirstLastNameDiasporaedOut, script, )
    end
end # type CorridorOut

const _property_types_CorridorOut = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("FirstLastNameGenderedOut")=>"FirstLastNameGenderedOut", Symbol("FirstLastNameOriginedOut")=>"FirstLastNameOriginedOut", Symbol("FirstLastNameDiasporaedOut")=>"FirstLastNameDiasporaedOut", Symbol("script")=>"String", )
OpenAPI.property_type(::Type{ CorridorOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CorridorOut[name]))}

function check_required(o::CorridorOut)
    true
end

function OpenAPI.validate_property(::Type{ CorridorOut }, name::Symbol, val)
end
