# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNameGeoSubdivisionIn

    BatchFirstLastNameGeoSubdivisionIn(;
        personalNames=nothing,
    )

    - personalNames::Vector{FirstLastNameGeoSubdivisionIn}
"""
Base.@kwdef mutable struct BatchFirstLastNameGeoSubdivisionIn <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNameGeoSubdivisionIn} }

    function BatchFirstLastNameGeoSubdivisionIn(personalNames, )
        OpenAPI.validate_property(BatchFirstLastNameGeoSubdivisionIn, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchFirstLastNameGeoSubdivisionIn

const _property_types_BatchFirstLastNameGeoSubdivisionIn = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{FirstLastNameGeoSubdivisionIn}", )
OpenAPI.property_type(::Type{ BatchFirstLastNameGeoSubdivisionIn }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNameGeoSubdivisionIn[name]))}

function check_required(o::BatchFirstLastNameGeoSubdivisionIn)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNameGeoSubdivisionIn }, name::Symbol, val)
end
