# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""APIServicesOut

    APIServicesOut(;
        apiServices=nothing,
    )

    - apiServices::Vector{APIServiceOut} : List of API Services
"""
Base.@kwdef mutable struct APIServicesOut <: OpenAPI.APIModel
    apiServices::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{APIServiceOut} }

    function APIServicesOut(apiServices, )
        OpenAPI.validate_property(APIServicesOut, Symbol("apiServices"), apiServices)
        return new(apiServices, )
    end
end # type APIServicesOut

const _property_types_APIServicesOut = Dict{Symbol,String}(Symbol("apiServices")=>"Vector{APIServiceOut}", )
OpenAPI.property_type(::Type{ APIServicesOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_APIServicesOut[name]))}

function check_required(o::APIServicesOut)
    true
end

function OpenAPI.validate_property(::Type{ APIServicesOut }, name::Symbol, val)
end
