# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BatchFirstLastNameReligionedOut
Represents the output of inferring the LIKELY religion from a list of personal names.

    BatchFirstLastNameReligionedOut(;
        personalNames=nothing,
    )

    - personalNames::Vector{FirstLastNameReligionedOut} : Classified names
"""
Base.@kwdef mutable struct BatchFirstLastNameReligionedOut <: OpenAPI.APIModel
    personalNames::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{FirstLastNameReligionedOut} }

    function BatchFirstLastNameReligionedOut(personalNames, )
        OpenAPI.validate_property(BatchFirstLastNameReligionedOut, Symbol("personalNames"), personalNames)
        return new(personalNames, )
    end
end # type BatchFirstLastNameReligionedOut

const _property_types_BatchFirstLastNameReligionedOut = Dict{Symbol,String}(Symbol("personalNames")=>"Vector{FirstLastNameReligionedOut}", )
OpenAPI.property_type(::Type{ BatchFirstLastNameReligionedOut }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BatchFirstLastNameReligionedOut[name]))}

function check_required(o::BatchFirstLastNameReligionedOut)
    true
end

function OpenAPI.validate_property(::Type{ BatchFirstLastNameReligionedOut }, name::Symbol, val)
end
